export const LOAD_STATUS = 'LOAD_STATUS'
export const SET_AUTH = 'SET_AUTH'
export const SET_THEME = 'SET_THEME'
export const LOAD_NEW_CHATS = 'LOAD_NEW_CHATS'
export const CLEAR_NEW_CHATS = 'CLEAR_NEW_CHATS'